version: '3.8'
services:
 app:
   container_name: WebAPI_LunaEdgeTest
   build:
      context: .
      dockerfile: Dockerfile 
 db:
   image: mysql:latest
   container_name: MySQL_LunaEdgeTest
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=LunaEdgeTest